package hyperv_wsman

import (
	"reflect"
	"runtime"
	"strings"
	"testing"
)

// assertShadowedIn は method が **本パッケージで定義されている** ことを検証する。
//
// 🔴 **`reflect.Type.MethodByName` の存在確認だけでは意味が無い。**
// ClientConfig は `*hyperv_winrm.ClientConfig` を埋め込んでいるため、本パッケージに
// 実装が無くても埋め込み側の昇格メソッドがメソッドセットに現れる。つまり
// 「メソッドが存在するか」だけ見ていると、**wsman 実装を消しても緑**になり、
// PowerShell への silent fallback をまったく検出できない。
//
// 2026-10-05 実測 (vm_dvd_drive.go の CreateVmDvdDrive を改名して確認):
//
//	                        FuncForPC(...).Name()                       FileLine
//	シャドウ済              hyperv-wsman.(*ClientConfig).CreateVmDvdDrive  vm_dvd_drive.go:61
//	昇格 (実装を消した状態)  hyperv-wsman.(*ClientConfig).CreateVmDvdDrive  <autogenerated>:1
//
// **シンボル名は同一**(Go は昇格ラッパーを外側の型名で命名する)。区別できるのは
// **定義元のファイル**だけで、昇格ラッパーは `<autogenerated>` になる。
//
// wantFile を明示的に渡させているのは、ソースから「定義されているファイル」を導くと
// 検証が循環して何も固定できなくなるため。期待値は人間が書く。
func assertShadowedIn(t *testing.T, method, wantFile string) {
	t.Helper()
	cType := reflect.TypeOf((*ClientConfig)(nil))
	m, ok := cType.MethodByName(method)
	if !ok {
		t.Fatalf("%s が ClientConfig に存在しない", method)
	}
	pc := m.Func.Pointer()
	file, _ := runtime.FuncForPC(pc).FileLine(pc)
	if !strings.HasSuffix(file, wantFile) {
		t.Errorf("%s の定義元が %q (期待: %q で終わる)。promotion のままだと <autogenerated> になり無条件 PS が解消しない",
			method, file, wantFile)
	}
}

// assertAllShadowedIn は同じファイルで定義されるメソッド群をまとめて検証する。
func assertAllShadowedIn(t *testing.T, wantFile string, methods ...string) {
	t.Helper()
	for _, m := range methods {
		assertShadowedIn(t, m, wantFile)
	}
}

// TestAssertShadowedIn_DetectsPromotion は検証そのものが機能していることを固定する。
//
// ClientConfig が埋め込み winrm から昇格しているだけのメソッドを 1 つ選び、
// assertShadowedIn が **それを本パッケージ定義と誤認しない** ことを確かめる。
// これが無いと「assertShadowedIn 自体が壊れていても全テストが緑」になる。
func TestAssertShadowedIn_DetectsPromotion(t *testing.T) {
	// GetVMSwitch は hyperv-wsman に実装が無く、埋め込み winrm から昇格している
	// (スイッチ CRUD は Backlog #46 で未着手)。2026-10-05 時点で昇格メソッドは 18 件ある。
	// (未シャドウのメソッドが 1 つも無くなったら、このテストは別のメソッドに差し替える)
	const promoted = "GetVMSwitch"
	cType := reflect.TypeOf((*ClientConfig)(nil))
	m, ok := cType.MethodByName(promoted)
	if !ok {
		t.Skipf("%s が ClientConfig に無い (インターフェースが変わった)", promoted)
	}
	pc := m.Func.Pointer()
	file, _ := runtime.FuncForPC(pc).FileLine(pc)
	if strings.HasSuffix(file, "vm_switch.go") {
		t.Fatalf("%s が本パッケージで実装された (%s)。このテストを未シャドウの別メソッドへ差し替えること", promoted, file)
	}
	if !strings.Contains(file, "autogenerated") {
		t.Errorf("昇格メソッド %s の定義元が %q。<autogenerated> を前提にした検出が成り立っていない。"+
			"assertShadowedIn の判定方法を見直すこと", promoted, file)
	}
}
