package hyperv_wsman

import (
	"path/filepath"
	"reflect"
	"runtime"
	"strings"
	"testing"
)

// assertShadowedIn は method が **本パッケージで定義されている** ことを検証する。
//
// 🔴 **`reflect.Type.MethodByName` の存在確認だけでは意味が無い。**
// ClientConfig は `*hyperv_winrm.ClientConfig` を埋め込んでいるため、本パッケージに
// 実装が無くても埋め込み側の昇格メソッドがメソッドセットに現れる。つまり
// 「メソッドが存在するか」だけ見ていると、**wsman 実装を消しても緑**になり、
// PowerShell への silent fallback をまったく検出できない。
//
// 2026-10-05 実測 (vm_dvd_drive.go の CreateVmDvdDrive を改名して確認):
//
//	                        FuncForPC(...).Name()                       FileLine
//	シャドウ済              hyperv-wsman.(*ClientConfig).CreateVmDvdDrive  vm_dvd_drive.go:61
//	昇格 (実装を消した状態)  hyperv-wsman.(*ClientConfig).CreateVmDvdDrive  <autogenerated>:1
//
// **シンボル名は同一**(Go は昇格ラッパーを外側の型名で命名する)。区別できるのは
// **定義元のファイル**だけで、昇格ラッパーは `<autogenerated>` になる。
//
// wantFile を明示的に渡させているのは、ソースから「定義されているファイル」を導くと
// 検証が循環して何も固定できなくなるため。期待値は人間が書く。
func assertShadowedIn(t *testing.T, method, wantFile string) {
	t.Helper()
	ok, file := shadowedIn(t, method, wantFile)
	if !ok {
		t.Errorf("%s の定義元が %q (期待: %q)。promotion のままだと <autogenerated> になり無条件 PS が解消しない\n  full path: %s",
			method, filepath.Base(file), wantFile, file)
	}
}

// shadowedIn は assertShadowedIn の**判定本体**。method の定義元ファイルが wantFile かを返す。
//
// 判定を関数に切り出しているのは、自己テスト (TestAssertShadowedIn_DetectsPromotion) が
// **この判定そのものを通れるように**するため。自己テスト側で同じロジックを書き直すと、
// 判定が壊れていても自己テストが独自実装で緑になり、何も守らない
// (実際にそう書いていて、判定を潰す変異が生き残った)。
//
// 比較は filepath.Base の完全一致。HasSuffix だと将来 shadow_vm.go のようなファイルを
// 足したときに wantFile="vm.go" が誤って一致する。
func shadowedIn(t *testing.T, method, wantFile string) (ok bool, file string) {
	t.Helper()
	cType := reflect.TypeOf((*ClientConfig)(nil))
	m, found := cType.MethodByName(method)
	if !found {
		t.Fatalf("%s が ClientConfig に存在しない", method)
	}
	pc := m.Func.Pointer()
	file, _ = runtime.FuncForPC(pc).FileLine(pc)
	return filepath.Base(file) == wantFile, file
}

// assertAllShadowedIn は同じファイルで定義されるメソッド群をまとめて検証する。
func assertAllShadowedIn(t *testing.T, wantFile string, methods ...string) {
	t.Helper()
	for _, m := range methods {
		assertShadowedIn(t, m, wantFile)
	}
}

// TestAssertShadowedIn_DetectsPromotion は shadowedIn の判定そのものが機能していることを固定する。
//
// 固定しているのは 2 点:
//
//	陰性: 昇格しているだけのメソッドを「本パッケージ定義」と判定しない
//	陽性: 実際にシャドウ済のメソッドは「本パッケージ定義」と判定する
//
// 陽性側が無いと「常に false を返す」実装でも陰性側が通る。陰性側が無いと
// 「常に true を返す」実装 (= 判定を潰す変異) が通る。両方で挟む。
//
// 併せて、昇格ラッパーの定義元が `<autogenerated>` になるという**ランタイム側の前提**も
// 固定する。これが崩れて内側 winrm の実ファイル名が返るようになると、
// shadowedIn は wantFile 一致で黙って緑になりうる。ここで落ちれば気付ける。
func TestAssertShadowedIn_DetectsPromotion(t *testing.T) {
	// GetVMSwitch は hyperv-wsman に実装が無く、埋め込み winrm から昇格している
	// (スイッチ CRUD は Backlog #46 で未着手)。2026-10-05 時点で昇格メソッドは 18 件ある。
	// (未シャドウのメソッドが 1 つも無くなったら、このテストは別のメソッドに差し替える)
	const promoted = "GetVMSwitch"

	ok, file := shadowedIn(t, promoted, "vm_switch.go")
	if ok {
		t.Fatalf("昇格メソッド %s を本パッケージ定義と判定した (定義元 %s)。"+
			"本パッケージで実装されたならこのテストを未シャドウの別メソッドへ差し替えること。"+
			"そうでなければ shadowedIn の判定が壊れている", promoted, file)
	}
	if !strings.Contains(file, "autogenerated") {
		t.Errorf("昇格メソッド %s の定義元が %q。<autogenerated> を前提にした検出が成り立っていない。"+
			"shadowedIn の判定方法を見直すこと", promoted, file)
	}

	// 陽性側: 実際にシャドウ済のメソッドは true になること。
	if ok, file := shadowedIn(t, "GetVmStatus", "vm_status.go"); !ok {
		t.Errorf("シャドウ済の GetVmStatus を本パッケージ定義と判定しなかった (定義元 %s)。"+
			"shadowedIn が常に false を返していないか", file)
	}
}
