package hyperv_wsman

import (
	"math"
	"reflect"
	"runtime"
	"strings"
	"testing"

	"github.com/r4sd/go-wsman/hyperv"
	"github.com/taliesins/terraform-provider-hyperv/api"
)

// assertShadowedIn は ClientConfig の method が本パッケージの wantFile で「直接定義」されている
// (= 埋め込み winrm からの promotion ではない) ことを検証する。
//
// reflect.MethodByName は promoted メソッドも含むため単なる存在チェックはトートロジーになる
// (シャドウを消しても winrm の promotion で通ってしまう)。promoted メソッドの実体は
// runtime 上 "<autogenerated>" ラッパーになるため、定義元ファイルが wantFile を指すことを
// 確認することで「無条件 PS が実際に解消されている」ことを機械検証する。
func assertShadowedIn(t *testing.T, method, wantFile string) {
	t.Helper()
	cType := reflect.TypeOf((*ClientConfig)(nil))
	m, ok := cType.MethodByName(method)
	if !ok {
		t.Fatalf("%s が ClientConfig に存在しない", method)
	}
	pc := m.Func.Pointer()
	file, _ := runtime.FuncForPC(pc).FileLine(pc)
	if !strings.HasSuffix(file, wantFile) {
		t.Errorf("%s の定義元が %q (期待: %q で終わる)。promotion のままだと <autogenerated> になり無条件 PS が解消しない",
			method, file, wantFile)
	}
}

// TestClientConfig_ImplementsHypervVmProcessorClient は ClientConfig が
// api.HypervVmProcessorClient を実装し、無条件 PS だった GetVmProcessors が本パッケージで
// シャドウイング (promotion ではなく直接定義) されていることを検証する。Create/Update は
// 埋め込み winrm から promotion されるため、ここでは検証しない。
func TestClientConfig_ImplementsHypervVmProcessorClient(t *testing.T) {
	var c *ClientConfig
	var _ api.HypervVmProcessorClient = c // コンパイル時チェック

	assertShadowedIn(t, "GetVmProcessors", "vm_processor.go")
}

// TestProcessorFromSettingData は CIM → provider の単位変換が正しいことを検証する。
// 特に Limit/Reservation の percent/1000 → percent 変換と、Weight の 1:1 (無変換) を固定する。
func TestProcessorFromSettingData(t *testing.T) {
	src := &hyperv.Msvm_ProcessorSettingData{
		VirtualQuantity:                4,
		Limit:                          75000, // 75%
		Reservation:                    25000, // 25%
		Weight:                         200,   // RelativeWeight と 1:1
		LimitProcessorFeatures:         true,  // → CompatibilityForMigrationEnabled
		LimitCPUID:                     true,  // → CompatibilityForOlderOperatingSystemsEnabled
		ExposeVirtualizationExtensions: true,
		HwThreadsPerCore:               2,
		MaxProcessorsPerNumaNode:       8,
		MaxNumaNodesPerSocket:          1,
		EnableHostResourceProtection:   true,
	}

	got := processorFromSettingData("my-vm", src)

	want := api.VmProcessor{
		VmName:                           "my-vm",
		CompatibilityForMigrationEnabled: true,
		CompatibilityForOlderOperatingSystemsEnabled: true,
		HwThreadCountPerCore:                         2,
		Maximum:                                      75, // 75000 / 1000
		Reserve:                                      25, // 25000 / 1000
		RelativeWeight:                               200,
		MaximumCountPerNumaNode:                      8,
		MaximumCountPerNumaSocket:                    1,
		EnableHostResourceProtection:                 true,
		ExposeVirtualizationExtensions:               true,
	}
	if !reflect.DeepEqual(got, want) {
		t.Errorf("processorFromSettingData mismatch:\n got=%+v\nwant=%+v", got, want)
	}
}

// TestProcessorFromSettingData_Defaults は Hyper-V 既定値 (Limit=100000=100%, Reserve=0,
// Weight=100) が provider の既定 (Maximum=100, Reserve=0, RelativeWeight=100) に写ることを
// 確認する。homelab の大半はこのデフォルト値なので、恒常 diff が出ないことの担保になる。
func TestProcessorFromSettingData_Defaults(t *testing.T) {
	src := &hyperv.Msvm_ProcessorSettingData{
		VirtualQuantity: 2,
		Limit:           100000,
		Reservation:     0,
		Weight:          100,
	}
	got := processorFromSettingData("vm", src)
	if got.Maximum != 100 {
		t.Errorf("Maximum: got %d, want 100", got.Maximum)
	}
	if got.Reserve != 0 {
		t.Errorf("Reserve: got %d, want 0", got.Reserve)
	}
	if got.RelativeWeight != 100 {
		t.Errorf("RelativeWeight: got %d, want 100", got.RelativeWeight)
	}
}

// TestApplyProcessorSettings_RoundTrip は逆変換 (applyProcessorSettings) が read 変換
// (processorFromSettingData) の逆になっていることを検証する。write→read で元の値に戻ること。
func TestApplyProcessorSettings_RoundTrip(t *testing.T) {
	want := api.VmProcessor{
		VmName:                           "vm",
		CompatibilityForMigrationEnabled: true,
		CompatibilityForOlderOperatingSystemsEnabled: true,
		HwThreadCountPerCore:                         2,
		Maximum:                                      75, // → Limit 75000
		Reserve:                                      25, // → Reservation 25000
		RelativeWeight:                               200,
		MaximumCountPerNumaNode:                      8,
		MaximumCountPerNumaSocket:                    1,
		EnableHostResourceProtection:                 true,
		ExposeVirtualizationExtensions:               true,
	}
	// 現行設定を模した struct (InstanceID/VirtualQuantity は保持されること)。
	p := &hyperv.Msvm_ProcessorSettingData{
		InstanceID:      "Microsoft:vm-guid\\proc",
		VirtualQuantity: 4,
	}
	applyProcessorSettings(p, want)

	if p.InstanceID != "Microsoft:vm-guid\\proc" {
		t.Errorf("InstanceID が保持されていない: %q", p.InstanceID)
	}
	if p.VirtualQuantity != 4 {
		t.Errorf("VirtualQuantity (vCPU) が保持されていない: %d", p.VirtualQuantity)
	}
	if p.Limit != 75000 {
		t.Errorf("Limit: got %d, want 75000 (Maximum×1000)", p.Limit)
	}
	if p.Reservation != 25000 {
		t.Errorf("Reservation: got %d, want 25000 (Reserve×1000)", p.Reservation)
	}
	// read 変換で元の api.VmProcessor に戻ること (VmName を合わせて比較)。
	got := processorFromSettingData("vm", p)
	if !reflect.DeepEqual(got, want) {
		t.Errorf("round-trip mismatch:\n got=%+v\nwant=%+v", got, want)
	}
}

// TestProcessorSettingsEqual は差分なしガードの判定を検証する (VmName は無視)。
func TestProcessorSettingsEqual(t *testing.T) {
	base := api.VmProcessor{Maximum: 100, Reserve: 0, RelativeWeight: 100}
	sameDiffName := base
	sameDiffName.VmName = "other"
	if !processorSettingsEqual(base, sameDiffName) {
		t.Error("VmName だけ違う場合は等しいと判定すべき")
	}
	diff := base
	diff.Maximum = 50
	if processorSettingsEqual(base, diff) {
		t.Error("Maximum が違う場合は等しくないと判定すべき")
	}
}

// TestHasZeroDowngrade は「非ゼロ→0」「true→false」の遷移検出を検証する。これらは go-wsman の
// ゼロ値非送信で反映できないため PS 委譲されるべきケース。
func TestHasZeroDowngrade(t *testing.T) {
	cur := api.VmProcessor{
		Maximum: 50, Reserve: 10, RelativeWeight: 200, HwThreadCountPerCore: 2,
		CompatibilityForMigrationEnabled: true, ExposeVirtualizationExtensions: true,
	}
	cases := []struct {
		name string
		want api.VmProcessor
		down bool
	}{
		{"reserve 10→0", api.VmProcessor{Maximum: 50, Reserve: 0, RelativeWeight: 200, HwThreadCountPerCore: 2, CompatibilityForMigrationEnabled: true, ExposeVirtualizationExtensions: true}, true},
		{"exposeVirt true→false", api.VmProcessor{Maximum: 50, Reserve: 10, RelativeWeight: 200, HwThreadCountPerCore: 2, CompatibilityForMigrationEnabled: true, ExposeVirtualizationExtensions: false}, true},
		{"compat true→false", api.VmProcessor{Maximum: 50, Reserve: 10, RelativeWeight: 200, HwThreadCountPerCore: 2, CompatibilityForMigrationEnabled: false, ExposeVirtualizationExtensions: true}, true},
		{"hwThread 2→0", api.VmProcessor{Maximum: 50, Reserve: 10, RelativeWeight: 200, HwThreadCountPerCore: 0, CompatibilityForMigrationEnabled: true, ExposeVirtualizationExtensions: true}, true},
		{"maximum 50→75 (upgrade)", api.VmProcessor{Maximum: 75, Reserve: 10, RelativeWeight: 200, HwThreadCountPerCore: 2, CompatibilityForMigrationEnabled: true, ExposeVirtualizationExtensions: true}, false},
		{"reserve 10→20 (non-zero)", api.VmProcessor{Maximum: 50, Reserve: 20, RelativeWeight: 200, HwThreadCountPerCore: 2, CompatibilityForMigrationEnabled: true, ExposeVirtualizationExtensions: true}, false},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			if got := hasZeroDowngrade(cur, tc.want); got != tc.down {
				t.Errorf("hasZeroDowngrade: got %v, want %v", got, tc.down)
			}
		})
	}
}

// TestCreateOrUpdateVmProcessors_Guards は空リスト no-op と複数エラーを検証する。
// 空リストは WsmanClient を触らず nil を返す (nil ポインタでも panic しない=書き込み 0 件の担保)。
func TestCreateOrUpdateVmProcessors_Guards(t *testing.T) {
	c := &ClientConfig{} // WsmanClient も埋め込み winrm も nil
	if err := c.CreateOrUpdateVmProcessors(t.Context(), "vm", nil); err != nil {
		t.Errorf("空リストは no-op であるべき: %v", err)
	}
	if err := c.CreateOrUpdateVmProcessors(t.Context(), "vm", []api.VmProcessor{}); err != nil {
		t.Errorf("空スライスは no-op であるべき: %v", err)
	}
	err := c.CreateOrUpdateVmProcessors(t.Context(), "vm", []api.VmProcessor{{}, {}})
	if err == nil {
		t.Error("2 件以上はエラーを返すべき")
	}
}

// TestClampInt は縮小変換の上限丸めを検証する (gosec G115 回避の防御が機能すること)。
func TestClampInt(t *testing.T) {
	if got := clampInt64(math.MaxUint64); got != math.MaxInt64 {
		t.Errorf("clampInt64(MaxUint64): got %d, want MaxInt64", got)
	}
	if got := clampInt64(42); got != 42 {
		t.Errorf("clampInt64(42): got %d, want 42", got)
	}
	if got := clampInt32(math.MaxUint64); got != math.MaxInt32 {
		t.Errorf("clampInt32(MaxUint64): got %d, want MaxInt32", got)
	}
	if got := clampInt32(7); got != 7 {
		t.Errorf("clampInt32(7): got %d, want 7", got)
	}
}
